name: Automated tests
on: push
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Unit tests
        run: npm run test:jest

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: End-to-end tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: npm run serve
          wait-on: 'http://localhost:9000'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
